<?php
    $cities =[
        'budapest' => 'Budapest (Ungarn)',
        'helsinki' => 'Helsinki (Finnland)',
        'basel' => 'Basel (Schweiz)',
        'zuerich' => 'Zürich (Schweiz)',
        'london' => 'London (United Kingdom)',
        'paris' => 'Paris (Frankreich)',
        'rome' => 'Rom (Italien)',
        'berlin' => 'Berlin (Deutschland)',
        'madrid' => 'Madrid (Spanien)',
        'lisbon' => 'Lissabon (Portugal)',
        'amsterdam' => 'Amsterdam (Niederlande)',
        'vienna' => 'Wien (Österreich)',
        'prague' => 'Prag (Tschechien)',
        'brussels' => 'Brüssel (Belgien)',
        'moscow' => 'Moskau (Russland)',
        'athens' => 'Athen (Griechenland)',
        'stockholm' => 'Stockholm (Schweden)',
        'oslo' => 'Oslo (Norwegen)',
        'copenhagen' => 'Kopenhagen (Dänemark)',
        'dublin' => 'Dublin (Irland)',
        'warsaw' => 'Warschau (Polen)',
        'budapest' => 'Budapest (Ungarn)',
        'prague' => 'Prag (Tschechien)',
        'bucharest' => 'Bukarest (Rumänien)',
        'zagreb' => 'Zagreb (Kroatien)',
        'vienna' => 'Wien (Österreich)',
        'bratislava' => 'Bratislava (Slowakei)',
        'ljubljana' => 'Ljubljana (Slowenien)',
        'belgrade' => 'Belgrad (Serbien)',
        'sofia' => 'Sofia (Bulgarien)',
        'ankara' => 'Ankara (Türkei)'
    ];
    ksort($cities) // das soritiert unsere stäte wahl alpahbetisch
?>
